// Generated by CoffeeScript 2.3.1
(function() {
  module.exports = function() {
    var aa;
    aa = [1, 2, 3, 4];
    aa.pop();
    aa.pop();
    aa.pop();
    return console.log(aa);
  };

}).call(this);

//# sourceMappingURL=tt.js.map
