// Generated by CoffeeScript 2.0.0-beta4
(function() {
  var AWS, Pinterest, PromisePool, campaigns, dynamoDB, token;

  AWS = require('aws-sdk');

  //request = require 'request-promise'
  dynamoDB = new AWS.DynamoDB({
    endpoint: 'http://localhost:8000',
    region: 'local'
  });

  token = void 0;

  campaigns = void 0;

  Pinterest = {
    getToken: async function() {
      var data;
      if (token) {
        return token;
      }
      data = (await (dynamoDB.query({
        TableName: "ApiAccessToken",
        ExpressionAttributeValues: {
          ":id": {
            S: "1446289"
          }
        },
        KeyConditionExpression: "clientId = :id"
      }).promise()));
      return token = data.Items[0].token.S;
    },
    getCompaign: function() {
      var data;
      if (campaigns) {
        return campaigns;
      }
      data = dynamoDB.scan({
        TableName: "PinterestCampaign"
      }).promise();
      return campaigns = data.Items;
    },
    worker: function() {
      var adGroupId;
      //    adGroup = undefined
      while (true) {
        if (campaigns.length === 0) {
          return null;
        }
        if (campaigns[-1].adGroupIds.length === 0) {
          campaigns.pop();
          continue;
        }
      }
      adGroupId = campaigns[-1].adGroupIds.pop();
      return dynamoDB.query({
        TableName: "PinterestAdGroup",
        ExpressionAttributeValues: {
          ":id": adGroupId
        },
        KeyConditionExpression: "adGroupId = :id"
      }).promise().then(function(data) {
        return console.log(data);
      });
    }
  };

  PromisePool = require('es6-promise-pool');

  module.exports = async function() {
    var pool;
    await Pinterest.getToken();
    await Pinterest.getCompaign();
    pool = new PromisePool(Pinterest.worker, 3);
    return pool.start().then(function() {
      return console.log("Done");
    });
  };

}).call(this);

//# sourceMappingURL=index.js.map
